service: dynamic-ephemeral-storage-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    STAGE: ${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::audio-uploads-dynamic-ephemeral-storage-test-prod/*'
        - 'arn:aws:s3:::audio-uploads-dynamic-ephemeral-storage-test-dev/*'
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
      Resource:
        - !Ref DemoSNSTopicFor512MB
        - !Ref DemoSNSTopicFor1GB
        - !Ref DemoSNSTopicFor3GB
        - !Ref DemoSNSTopicFor5GB
        - !Ref DemoSNSTopicFor10GB

params:
  prod:
    s3UploadBucket: audio-uploads-dynamic-ephemeral-storage-test-prod
    512MBSnsTopic: des-demo-encode-512MB-prod
    1GBSnsTopic: des-demo-encode-1GB-prod
    3GBSnsTopic: des-demo-encode-3GB-prod
    5GBSnsTopic: des-demo-encode-5GB-prod
    10GBSnsTopic: des-demo-encode-10GB-prod
  dev:
    s3UploadBucket: audio-uploads-dynamic-ephemeral-storage-test-dev
    512MBSnsTopic: des-demo-encode-512MB-dev
    1GBSnsTopic: des-demo-encode-1GB-dev
    3GBSnsTopic: des-demo-encode-3GB-dev
    5GBSnsTopic: des-demo-encode-5GB-dev
    10GBSnsTopic: des-demo-encode-10GB-dev

functions:
  step0Publisher:
    handler: step0.publisher
    events:
      - s3:
          bucket: ${param:s3UploadBucket}
          event: s3:ObjectCreated:*

  512MBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 512
    events:
      - sns:
          arn: !Ref DemoSNSTopicFor512MB
          topicName: ${param:512MBSnsTopic}

  1GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 1024
    events:
      - sns:
          arn: !Ref DemoSNSTopicFor1GB
          topicName: ${param:1GBSnsTopic}

  3GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 3072
    events:
      - sns:
          arn: !Ref DemoSNSTopicFor3GB
          topicName: ${param:3GBSnsTopic}

  5GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 5120
    events:
      - sns:
          arn: !Ref DemoSNSTopicFor5GB
          topicName: ${param:5GBSnsTopic}

  10GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 10240
    events:
      - sns:
          arn: !Ref DemoSNSTopicFor10GB
          topicName: ${param:10GBSnsTopic}

resources:
  Resources:
    DemoSNSTopicFor512MB:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${param:512MBSnsTopic}
        KmsMasterKeyId: ${ssm:kms-sns-key-id}

    DemoSNSTopicFor1GB:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${param:1GBSnsTopic}
        KmsMasterKeyId: ${ssm:kms-sns-key-id}

    DemoSNSTopicFor3GB:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${param:3GBSnsTopic}
        KmsMasterKeyId: ${ssm:kms-sns-key-id}

    DemoSNSTopicFor5GB:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${param:5GBSnsTopic}
        KmsMasterKeyId: ${ssm:kms-sns-key-id}

    DemoSNSTopicFor10GB:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: ${param:10GBSnsTopic}
        KmsMasterKeyId: ${ssm:kms-sns-key-id}
