service: dynamic-ephemeral-storage-example

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  environment:
    STAGE: ${opt:stage, self:provider.stage}
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
      Resource:
        - 'arn:aws:s3:::audio-uploads-dynamic-ephemeral-storage-test-prod/*'
        - 'arn:aws:s3:::audio-uploads-dynamic-ephemeral-storage-test-dev/*'
    - Effect: Allow
      Action:
        - sns:Publish
        - sns:Subscribe
      Resource:
        - 'arn:aws:sns:us-east-1:260462628773:encode-512MB-dev'
        - 'arn:aws:sns:us-east-1:260462628773:encode-512MB-prod'
        - 'arn:aws:sns:us-east-1:260462628773:encode-1GB-dev'
        - 'arn:aws:sns:us-east-1:260462628773:encode-1GB-prod'
        - 'arn:aws:sns:us-east-1:260462628773:encode-3GB-dev'
        - 'arn:aws:sns:us-east-1:260462628773:encode-3GB-prod'
        - 'arn:aws:sns:us-east-1:260462628773:encode-5GB-dev'
        - 'arn:aws:sns:us-east-1:260462628773:encode-5GB-prod'
        - 'arn:aws:sns:us-east-1:260462628773:encode-10GB-dev'
        - 'arn:aws:sns:us-east-1:260462628773:encode-10GB-prod'
  
params:
  prod:
    s3UploadBucket: audio-uploads-dynamic-ephemeral-storage-test-prod
    512MBSnsTopic: encode-512MB-prod
    1GBSnsTopic: encode-1GB-prod
    3GBSnsTopic: encode-3GB-prod
    5GBSnsTopic: encode-5GB-prod
    10GBSnsTopic: encode-10GB-prod
  dev:
    s3UploadBucket: audio-uploads-dynamic-ephemeral-storage-test-dev
    512MBSnsTopic: encode-512MB-dev
    1GBSnsTopic: encode-1GB-dev
    3GBSnsTopic: encode-3GB-dev
    5GBSnsTopic: encode-5GB-dev
    10GBSnsTopic: encode-10GB-dev

functions:
  step0Publisher:
    handler: step0.publisher
    events:
      - s3:
          bucket: ${param:s3UploadBucket}
          event: s3:ObjectCreated:*
  
  512MBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 512
    events:
      - sns: ${param:512MBSnsTopic}
    
  1GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 1024
    events:
      - sns: ${param:1GBSnsTopic}
    
  3GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 3072
    events:
      - sns: ${param:3GBSnsTopic}
    
  5GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 5120
    events:
      - sns: ${param:5GBSnsTopic}
    
  10GBHandler:
    handler: audioProcessor.encode
    ephemeralStorageSize: 10240
    events:
      - sns: ${param:10GBSnsTopic}
  